### ISSUE TITLE
Spazi tra i vari paragrafi

### ISSUE THREAD

**Issue by KuraudioITA** [dejawho/Oathsworn-ita-translation#10]
Ciao, 

sto cercando a tempo perso di aggiungere gli spazi ai primi paragrafi come nell'originale. 
Mi sono imbattutto in questo buttone che nella versione 1.4 non c'è (btn_2a_50_3__b) ma è presente nella versione tradotta.
Puoi per favore controllare e verificare che si possa cancellare?

Prossimamente ti manderò il file con gli spazi :)

**Comment by KuraudioITA** [comment]
Ciao,

alla fine ho preso tutto il file e ho aggiunto tutti gli spazi esattamente come sono nel file originale.
Ho anche corretto un po' di errori di \'singolare invece che plurale\'
Ho corretto alcune frasi che non erano tradotte come \"Scegliete un\'opzione\"
Ho corretto alcune frasi che si ripetevano ma che erano state tradotte in maniera diversa, per rendere il tutto più congruente.

Ho notato pure che ci sono un sacco di \" senza il backslash, quindi li ho cambiati in \' dove il testo prevedeva appunto di richiedere una parola in virgolette. Ho usato la virgoletta singola perchè quella doppia è usata per il parlato.

**Comment by KuraudioITA** [comment]
https://drive.google.com/file/d/1gG8nwdx1m9gAdufRCLKBsP9ESVT2OCpq/view?usp=sharing

**Comment by dejawho** [comment]
Ciao, presa la tua roba ed unita con la mia, ho dovuto fare l'unione a mano dato che pure io avevo modificato parecchie cose, spero di non aver perso nulla (sono stato abbastanza attento ma c'erano una marea di conflitti). Per sicurezza ho deciso di lasciare il bottone btn_2a_50_3__b , si può cancellare e l'app si riesce a rebuildare, ma una stringa in più non fa male quindi l'ho lasciato
